name: Cypress

on:
  push:
  workflow_dispatch:
    
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        settings: [{ baseUrl: 'https://dev.fakturaonline.cz', domain: 'CZ'}]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Install dependencies
        run: yarn install --immutable

      - name: Run Cypress tests
        env:
          CYPRESS_BASE_URL: ${{ matrix.settings.baseUrl }}
          CYPRESS_testUser: ${{ secrets[format('TEST_USER_{0}', matrix.settings.domain)] }}
          CYPRESS_testUserPassword: ${{ secrets[format('TEST_USER_PASSWORD_{0}', matrix.settings.domain)] }}
          CYPRESS_domain: ${{ matrix.settings.domain }}
        uses: cypress-io/github-action@v6
        with:
          browser: chrome